# Copyright 2016 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This builder may need to run Rails build commands, so it uses the Ruby base
# image to get Ruby and its dependencies.
FROM gcr.io/google-appengine/ruby:$BASE_TAG

# Install cloud_sql_proxy in case it is needed by Rails asset precompilation.
RUN mkdir /buildstep && mkdir /cloudsql
RUN curl https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 \
        > /buildstep/cloud_sql_proxy \
    && chmod a+x /buildstep/cloud_sql_proxy

# Install the build scripts.
COPY build_app/ /buildstep/
COPY shared/ /buildstep/

# The entry point runs the build script.
ENTRYPOINT ["/buildstep/run_build_step.sh"]
