require "rake/testtask"

DEFAULT_PROJECT = "google-appengine"

::Dir.chdir ::File.dirname __FILE__

desc "Build local docker image for base image"
task "build:local", :name do |t, args|
  name = args[:name] || "appengine-ruby-base"
  ::Dir.chdir "image_files" do
    sh "docker build --pull --no-cache -t #{name}" +
      " --build-arg RUNTIME_DISTRIBUTION=ruby-runtime-jessie-unstable ."
  end
end

desc "Build to a given project"
task "build:project", :project, :tag do |t, args|
  project = args[:project]
  fail "Project name required" unless project
  tag = args[:tag] || "latest"
  sh "./build.sh gcr.io/#{project}/ruby:#{tag}"
end

desc "Build to a given tag on the canonical image path"
task "build:tag", :tag do |t, args|
  tag = args[:tag]
  fail "Tag name required" unless tag
  sh "./build.sh gcr.io/#{DEFAULT_PROJECT}/ruby:#{tag}"
end

Rake::TestTask.new("test:base:only") do |t|
  t.test_files = FileList['test/tb_*.rb']
end

Rake::TestTask.new("test:cases:only") do |t|
  t.test_files = FileList['test/tc_*.rb']
end

desc "Build local base image and run base image tests"
task "test:base" => ["build:local", "test:base:only"]

desc "Build local base image and run use case tests"
task "test:cases" => ["build:local", "test:cases:only"]

desc "Run all tests"
task "test:only" => ["test:base:only", "test:cases:only"]

desc "Build local base image and run all tests"
task :test => ["build:local", "test:base:only", "test:cases:only"]

task :default => :test
