#!/bin/bash

# Copyright 2017 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

SCRIPT=$1

SQL_TIMEOUT=10

if [ -f "/build_tools/credentials.json" ]; then
  export GOOGLE_APPLICATION_CREDENTIALS=/build_tools/credentials.json
fi

if [ -n "${BUILD_CLOUDSQL_INSTANCES}" ]; then
  if [ -z "${GOOGLE_APPLICATION_CREDENTIALS}" -a -n "${GOOGLE_ACCESS_TOKEN_FILE}" ]; then
    TOKEN_PARAM="-token=$(cat ${GOOGLE_ACCESS_TOKEN_FILE})"
  else
    TOKEN_PARAM=
  fi
  rm -f /build_tools/cloud_sql_proxy.log
  touch /build_tools/cloud_sql_proxy.log
  /build_tools/cloud_sql_proxy -dir=/cloudsql ${TOKEN_PARAM} -instances=${BUILD_CLOUDSQL_INSTANCES} > /build_tools/cloud_sql_proxy.log 2>&1 &
  if (timeout ${SQL_TIMEOUT}s tail -f --lines=+1 /build_tools/cloud_sql_proxy.log &) | grep -qe 'Ready for new connections'; then
    echo "Started cloud_sql_proxy."
  else
    >&2 echo "ERROR: Failed to start cloud_sql_proxy"
    >&2 cat /build_tools/cloud_sql_proxy.log
    exit 1
  fi
fi

cd /app
sh -c "$SCRIPT"
