# Copyright 2016 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Use the Ruby base image to get Ruby and its dependencies.
FROM gcr.io/google-appengine/ruby:$BASE_IMAGE_TAG

# Install the build script and dockerfile templates.
RUN mkdir /buildstep
COPY gen_dockerfile/ /buildstep/
COPY shared/ /buildstep/

# The entry point runs the build script.
ENTRYPOINT ["/buildstep/run_build_step.sh"]
