# Copyright 2016 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

require "rake/testtask"
require "erb"

STEPS = ["build_app", "gen_dockerfile"]
DEFAULT_PROJECT = "cloud-builders"

::Dir.chdir(::File.dirname __FILE__)

def image_for_step step
  "ruby-#{step.gsub '_', '-'}"
end

STEPS.each do |step|
  step_image = image_for_step step

  desc "Build local docker image for #{step_image}"
  task "build:#{step}:local", :name do |t, args|
    name = args[:name] || step_image
    ::Dir.chdir "build_steps" do
      sh "docker build --pull --no-cache -t #{name} -f #{step}/Dockerfile ."
    end
  end

  desc "Build #{step_image} to a given project"
  task "build:#{step}:project", :project, :tag do |t, args|
    project = args[:project]
    fail "Project name required" unless project
    tag = args[:tag] || "latest"
    sh "./build_#{step}.sh gcr.io/#{project}/#{step_image}:#{tag}"
  end

  desc "Build #{step_image} to a given tag on the canonical image path"
  task "build:#{step}:tag", :tag do |t, args|
    tag = args[:tag]
    fail "Tag name required" unless tag
    sh "./build_#{step}.sh gcr.io/#{DEFAULT_PROJECT}/#{step_image}:#{tag}"
  end
end

desc "Build local docker image for all steps"
task "build:local" => STEPS.map { |step| "build:#{step}:local" }

desc "Build all steps to a given project"
task "build:project", :project, :tag do |t, args|
  project = args[:project]
  fail "Project name required" unless project
  tag = args[:tag] || "latest"
  STEPS.each do |step|
    step_image = image_for_step step
    sh "./build_#{step}.sh gcr.io/#{project}/#{step_image}:#{tag}"
  end
end

desc "Build all steps to a given tag on the canonical image path"
task "build:tag", :tag do |t, args|
  tag = args[:tag]
  fail "Tag name required" unless tag
  STEPS.each do |step|
    step_image = image_for_step step
    sh "./build_#{step}.sh gcr.io/#{DEFAULT_PROJECT}/#{step_image}:#{tag}"
  end
end

desc "Generate pipeline ruby.yaml"
task "gen_pipeline", :project, :tag do |t, args|
  project = args[:project] || DEFAULT_PROJECT
  tag = args[:tag] || "latest"
  sh "cat ruby.yaml.in | " \
    "sed -e \"s|\\$PROJECT|#{project}|g\" | " \
    "sed -e \"s|\\$TAG|#{tag}|g\" | " \
    "cat > ruby.yaml"
end

Rake::TestTask.new "test:only" do |t|
  t.test_files = FileList['test/tc_*.rb']
end

desc "Build local docker image and run tests for all steps"
task :test => ["build:local", "test:only"]

task :default => :test
