# Copyright 2016 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

require "rake/testtask"
require "erb"

::Dir.chdir(::File.dirname __FILE__)


desc "Build local docker image for build tools"
task "build:tools:local", :image do |t, args|
  image = args[:image] || "ruby-build-tools"
  ::Dir.chdir "build_tools" do
    sh "cp Dockerfile.in Dockerfile"
    sh "docker build --no-cache -t #{image} ."
  end
end

desc "Build local docker image for dockerfile generator"
task "build:generator:local", [:image, :build_tools_image] do |t, args|
  image = args[:image] || "ruby-generate-dockerfile"
  build_tools_image = args[:build_tools_image] || "ruby-build-tools"
  ::Dir.chdir "generate_dockerfile" do
    sh "sed -e 's|$BASE_IMAGE|gcr.io/google-appengine/ruby:staging|g;" \
      " s|$BUILD_TOOLS_IMAGE|#{build_tools_image}|g'" \
      " < Dockerfile.in > Dockerfile"
    sh "docker build --no-cache -t #{image} ."
  end
end

desc "Build local docker images for new builder"
task "build:local" => ["build:tools:local", "build:generator:local"]

Rake::TestTask.new "test:only" do |t|
  t.test_files = FileList['test/test_*.rb']
end

desc "Build local docker image and run tests for all steps"
task :test => ["build:local", "test:only"]

task :default => :test
