# Copyright 2016 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

require "rake/testtask"
require "erb"

STEPS = ["build_app", "gen_dockerfile"]
DEFAULT_PROJECT = "cloud-builders"
DEFAULT_TAG = "latest"

::Dir.chdir(::File.dirname __FILE__)

STEPS.each do |step|
  desc "Build local docker image for #{step}"
  task "build:#{step}:local", :image do |t, args|
    image = args[:image] || "ruby-#{step.gsub '_', '-'}"
    ::Dir.chdir "build_steps" do
      sh "sed -e 's/$BASE_TAG/latest/g'" \
        " < #{step}/Dockerfile.in > #{step}/Dockerfile"
      sh "docker build --pull --no-cache -t #{image} -f #{step}/Dockerfile ."
    end
  end

  desc "Build #{step} to a given tag and project"
  task "build:#{step}", :tag, :project do |t, args|
    tag = args[:tag] || DEFAULT_TAG
    project = args[:project] || DEFAULT_PROJECT
    sh "./build_#{step}.sh #{tag} #{project}"
  end
end

desc "Build local docker image for all steps"
task "build:local" => STEPS.map { |step| "build:#{step}:local" }

desc "Generate pipeline ruby.yaml"
task "build:pipeline", :tag, :project do |t, args|
  tag = args[:tag] || DEFAULT_TAG
  project = args[:project] || DEFAULT_PROJECT
  sh "./build_pipeline.sh #{tag} #{project}"
end

desc "Build the pipeline and all steps to a given tag and project"
task "build", :tag, :project do |t, args|
  tag = args[:tag] || DEFAULT_TAG
  project = args[:project] || DEFAULT_PROJECT
  sh "./build.sh #{tag} #{project}"
end

Rake::TestTask.new "test:only" do |t|
  t.test_files = FileList['test/tc_*.rb']
end

desc "Build local docker image and run tests for all steps"
task :test => ["build:local", "test:only"]

task :default => :test
